engines: 
  eslint:
    enabled: true
    checks:
      import/no-unresolved:
        enabled: false
  fixme:
    enabled: true
    
ratings:
   paths:
   - "server/src/**.js"
   - "client/**/*.js"
   - "client/**/*.jsx"

exclude_paths:
- ".nyc_output/"
- "**.min.js"
- "**.min.css"
- "node_modules/"
- "template/"
- "client/src/__tests__/"
- "client/config/"
- "client/coverage/"
- "client/reports/"
- "client/scripts/"
- "client/src/assets/"
- "server/config/"
- "server/coverage/"
- "server/src/migrations/"
- "server/src/models/"
- "server/src/seeders/"
- "server/tests/"
- "server/src/validations/"
- "nightwatch.conf.js"
- "gulpfile.babel.js"
- "webpack.config.*.js"
