engines: 
  eslint:
    enabled: true
    checks:
      import/no-unresolved:
        enabled: false
    
ratings:
   paths:
   - "server/src/**.js"

exclude_paths:
- "node_modules/"
- ".nyc_output"
- "coverage"
- "**.min.js"
- "**.min.css"
- "template"
- "server/src/seeders"
- "server/src/models"
- "server/src/migrations"
- "test"
