jshint:
  enabled: false
  
coffeescript:
  enabled: false

scss:
  enabled: false
  
sass:
  enabled: true
  config_file: .sass-lint.yml

eslint:
  enabled: true
  config_file: .hound.eslintrc
  ignore_file: .eslintignore

fail_on_violations: true
