FORMAT: 1A

# More Recipes [api/v1]

More-Recipes is an API provides a platform for users to share the awesome and exciting recipes idea they have invented or learnt.  This is version 1 of the API.

# Group User

Resources related to users in the API.

## Create a New Account [POST /users/signup]

You may create a new account using this action. It takes a JSON object containing user details.

+ Attributes

    + firstname (string, required) - The user's firstname.
    + lastname (string, required) - The user's lastname.
    + username (string, required) - The user's chosen username.
    + email (string, required) - The user's email address.
    + password (string, required) - The user's chosen password.
    + aboutMe (string, optional) - Information about User.
    + occupation (string, optional) - The user's occupation.

+ Request (application/json)

        {
            "firstname": "Iveren",
            "lastname": "Shaguy",
            "username": "iverenshaguy",
            "email": "iverenshaguy@gmail.com",
            "password": "iverenshaguy",
            "passwordConfirm": "iverenshaguy",
            "aboutMe": "Food lover. Bookworm",
            "occupation": "Software Developer",
        }

+ Response 201 (application/json)

    + Headers

            Location: /users/1
    
    + Body

            {
                "succes": true,
                "token": 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTE1NDQ0NzkwLCJleHAiOjE1MTU1MzExOTB9.6d1VznIz8slZFioUzvC4KNGDlz_YsUNy95g2LPaEnJE'
            }

## Authenticate User [POST /users/signin]

You may signin to your account using this action. It takes a JSON object containing user details.

+ Attributes
    + email (string, required) - The user's email address.
    + password (string, required) - The user's password.

+ Request (application/json)

        {
            "email": "iverenshaguy@gmail.com",
            "password": "iverenshaguy"
        }

+ Response 200 (application/json)

    + Headers

            Location: /users/1
    
    + Body

            {
                "succes": true,
                "token": 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTE1NDQ0NzkwLCJleHAiOjE1MTU1MzExOTB9.6d1VznIz8slZFioUzvC4KNGDlz_YsUNy95g2LPaEnJE'
            }

## View User Profile [GET /users/profile]

This allows you to view your user details

+ Request (application/json)

    + Headers

            token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTE1NDQ0NzkwLCJleHAiOjE1MTU1MzExOTB9.6d1VznIz8slZFioUzvC4KNGDlz_YsUNy95g2LPaEnJE'

+ Response 200 (application/json)

        {
            "id": 1,
            "firstname": "Iveren",
            "lastname": "Shaguy",
            "username": "iverenshaguy",
            "email": "iverenshaguy@gmail.com",
            "passwordHash": "000000100007a12016262f8e438082795b2154dae2c51201fe24c8007b4a11507183a1f9cf425de1218dac3804b30c7412f34d0c8cee1332",
            "aboutMe": "Smart",
            "occupation": "Software Developer",
            "profilePic": null,
            "coverPhoto": null,
            "createdAt": "2017-10-30T00:47:03.687Z",
            "updatedAt": "2017-10-30T00:47:03.687Z"
        }

### View Favorite Recipes [GET /users/{userId}/recipes]

+ Parameters
    + userId: `1` (required, number) - ID of the User in form of an integer.

+ Request (application/json)

    + Headers

            token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTE1NDQ0NzkwLCJleHAiOjE1MTU1MzExOTB9.6d1VznIz8slZFioUzvC4KNGDlz_YsUNy95g2LPaEnJE'

+ Response 200 (application/json)

        [
            {
                "id": 2,
                "recipeName": "Fried Rice",
                "recipeImage": null,
                "prepTime": "30 Minutes",
                "cookTime": "20 Minutes",
                "totalTime": "1 Hour",
                "difficulty": "Normal",
                "extraInfo": "Nigerian Party Staple",
                "vegetarian": false,
                "ingredients": [
                    "2 Cups of Rice",
                    "1 Kilo of Chicken"
                ],
                "preparations": [
                    "Cut the chicken into small pieces, season and leave to marinate for 1 hour. This can be done in advance to save time",
                    "Boil on low heat for 25 minutes with little water to cook and preserve the chicken stock.",
                    "Cut ingredients into small pieces"
                ],
                "directions": [
                    "Parboil Rice till half done",
                    "Steam ingredients in oil till almost soft"
                ],
                "createdAt": "2017-10-30T00:47:03.687Z",
                "updatedAt": "2017-10-30T00:47:03.687Z",
                "userId": 2
            },
            {
                "id": 3,
                "recipeName": "Rice and Beans",
                "recipeImage": null,
                "prepTime": "30 Minutes",
                "cookTime": "20 Minutes",
                "totalTime": "1 Hour",
                "difficulty": "Normal",
                "extraInfo": "",
                "vegetarian": false,
                "ingredients": [
                    "2 Cups of Rice",
                    "1.5 Cups of Beans",
                    "1 kilo of chicken"
                ],
                "preparations": [
                    "Cut the chicken into small pieces, season and leave to marinate for 1 hour. This can be done in advance to save time",
                    "Boil on low heat for 25 minutes with little water to cook and preserve the chicken stock."
                ],
                "directions": [
                    "Parboil Rice till half done",
                    "Cook beans with onions till almost done"
                ],
                "createdAt": "2017-10-30T00:47:03.687Z",
                "updatedAt": "2017-10-30T00:47:03.687Z",
                "userId": 3
            },
            {
                "id": 4,
                "recipeName": "Beans and Plantain",
                "recipeImage": null,
                "prepTime": "30 Minutes",
                "cookTime": "20 Minutes",
                "totalTime": "1 Hour",
                "difficulty": "Normal",
                "extraInfo": "",
                "vegetarian": true,
                "ingredients": [
                    "2 Cups of Beans",
                    "3 Plantains"
                ],
                "preparations": [
                    "Soak beans for 1 hour before cooking to reduce bloating"
                ],
                "directions": [
                    "Cook beans with Onions till soft",
                    "Add sliced plantains and ingredients and cook on low heat for another 5 minutes"
                ],
                "createdAt": "2017-10-30T00:47:03.687Z",
                "updatedAt": "2017-10-30T00:47:03.687Z",
                "userId": 5
            },
            ...
        ]      

# Group Recipe

Resources related to recipes in the API.

## Recipes [/recipes]

A Recipe Object has the following attributes:

+ Attributes

    + id (number) - Recipe id
    + recipeName (string) - Recipe Name
    + prepTime (string) - Recipe Preparation Time
    + cookTime (string) - Recipe Cook Time
    + totalTime (string) - Total Time
    + difficulty (string) - A List of Strings to Choose from
    + extraInfo (string) - Extra Information about Recipe
    + vegetarian (string) - Boolean showing if suitable for vegetarians
    + ingredients (array) - Array of ingredients
    + preparations (array) - Array of preparation steps
    + directions (array) - Array of direction steps
    + rating (number) - Float of Average Recipe rating
    + upvotes (number) - Sum of recipe upvotes
    + downvotes (number) - Sum of recipe downvotes
    + views (number) - Sum of recipe views

### Get All Recipes in the App [GET /recipes{?page,limit}]

+ Parameters

    + page: 3 (number, optional) - Page number to show.
    + limit: 10 (number, optional) - Number of items per page.

+ Request (application/json)

    + Headers

            token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTE1NDQ0NzkwLCJleHAiOjE1MTU1MzExOTB9.6d1VznIz8slZFioUzvC4KNGDlz_YsUNy95g2LPaEnJE'

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "recipeName": "Coconut Rice",
                "recipeImage": null,
                "prepTime": "30 Minutes",
                "cookTime": "20 Minutes",
                "totalTime": "1 Hour",
                "difficulty": "Normal",
                "extraInfo": "",
                "vegetarian": false,
                "ingredients": [
                    "2 Cups of Rice",
                    "1 Coconut"
                ],
                "preparations": [
                    "Cut the chicken into small pieces, season and leave to marinate for 1 hour. This can be done in advance to save time",
                    "Boil on low heat for 25 minutes with little water to cook and preserve the chicken stock.",
                    "Grate coconut and strain milk from it by boiling for a few minutes"
                ],
                "directions": [
                    "Parboil Rice till half done",
                    "Put already fried tomato stew on fire, add water and seasoning to taste"
                ],
                "createdAt": "2017-10-30T00:47:03.687Z",
                "updatedAt": "2017-10-30T00:47:03.687Z",
                "userId": 1,
                "rating": "3.5000000000000000",
                "likes": [
                    {
                        "upvote": true
                    },
                    {
                        "upvote": true
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    }
                ]
            },
            {
                "id": 2,
                "recipeName": "Fried Rice",
                "recipeImage": null,
                "prepTime": "30 Minutes",
                "cookTime": "20 Minutes",
                "totalTime": "1 Hour",
                "difficulty": "Normal",
                "extraInfo": "Nigerian Party Staple",
                "vegetarian": false,
                "ingredients": [
                    "2 Cups of Rice",
                    "1 Kilo of Chicken"
                ],
                "preparations": [
                    "Cut the chicken into small pieces, season and leave to marinate for 1 hour. This can be done in advance to save time",
                    "Boil on low heat for 25 minutes with little water to cook and preserve the chicken stock.",
                    "Cut ingredients into small pieces"
                ],
                "directions": [
                    "Parboil Rice till half done",
                    "Steam ingredients in oil till almost soft"
                ],
                "createdAt": "2017-10-30T00:47:03.687Z",
                "updatedAt": "2017-10-30T00:47:03.687Z",
                "userId": 2,
                "rating": "4.5000000000000000",
                "likes": [
                    {
                        "upvote": true
                    },
                    {
                        "upvote": true
                    },
                    {
                        "upvote": true
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    }
                ]
            },
            {
                "id": 3,
                "recipeName": "Rice and Beans",
                "recipeImage": null,
                "prepTime": "30 Minutes",
                "cookTime": "20 Minutes",
                "totalTime": "1 Hour",
                "difficulty": "Normal",
                "extraInfo": "",
                "vegetarian": false,
                "ingredients": [
                    "2 Cups of Rice",
                    "1.5 Cups of Beans",
                    "1 kilo of chicken"
                ],
                "preparations": [
                    "Cut the chicken into small pieces, season and leave to marinate for 1 hour. This can be done in advance to save time",
                    "Boil on low heat for 25 minutes with little water to cook and preserve the chicken stock."
                ],
                "directions": [
                    "Parboil Rice till half done",
                    "Cook beans with onions till almost done"
                ],
                "createdAt": "2017-10-30T00:47:03.687Z",
                "updatedAt": "2017-10-30T00:47:03.687Z",
                "userId": 3,
                "rating": "5.0000000000000000",
                "likes": [
                    {
                        "upvote": true
                    },
                    {
                        "upvote": true
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    }
                ]
            },
            {
                "id": 4,
                "recipeName": "Beans and Plantain",
                "recipeImage": null,
                "prepTime": "30 Minutes",
                "cookTime": "20 Minutes",
                "totalTime": "1 Hour",
                "difficulty": "Normal",
                "extraInfo": "",
                "vegetarian": true,
                "ingredients": [
                    "2 Cups of Beans",
                    "3 Plantains"
                ],
                "preparations": [
                    "Soak beans for 1 hour before cooking to reduce bloating"
                ],
                "directions": [
                    "Cook beans with Onions till soft",
                    "Add sliced plantains and ingredients and cook on low heat for another 5 minutes"
                ],
                "createdAt": "2017-10-30T00:47:03.687Z",
                "updatedAt": "2017-10-30T00:47:03.687Z",
                "userId": 5,
                "rating": "4.5000000000000000",
                "likes": [
                    {
                        "upvote": true
                    },
                    {
                        "upvote": true
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    }
                ]
            },
            ...
        ]

### Create a New Recipe [POST]

You may add you own recipe using this action. It takes a JSON object containing a recipe.

+ Attributes

    + recipeName (string, required) - Recipe Name
    + prepTime (string, optional) - Recipe Preparation Time
    + cookTime (string, optional) - Recipe Cook Time
    + totalTime (string, required) - Total Time
    + difficulty (enum[string], optional) - A List of Strings to Choose from
    + extraInfo (string, optional) - Extra Information about Recipe
    + vegetarian (string, optional) - Boolean showing if suitable for vegetarians
    + ingredients (array, required) - Array of ingredients
    + preparations (array, optional) - Array of preparation steps
    + directions (array, required) - Array of direction steps

    + Difficulty Values
        + `Easy`
        + `Normal`
        + `A Bit Difficult'
        + `Difficult'
        + `Very Difficult'


+ Request (apllication/json)

    + Headers

            token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTE1NDQ0NzkwLCJleHAiOjE1MTU1MzExOTB9.6d1VznIz8slZFioUzvC4KNGDlz_YsUNy95g2LPaEnJE'

    + Body

            {
                "recipeName": "Pounded Yam",
                "prepTime": "30 Minutes",
                "cookTime": "20 Minutes",
                "totalTime": "1 Hour",
                "difficulty": "A Bit Difficult",
                "extraInfo": "Can be eaten with any of the soups in my other recipes",
                "vegetarian": "false",
                "ingredients": ["1 tuber of yam"],
                "preparations": [
                    "Cut Yam into small pieces",
                    "Make sure every thing that isn't yam is removed from the cut pieces",
                    "Boil Yam in plain water (without salt) till soft, but not too soft"
                ],
                "directions": [
                    "Put about 2 pieces of yam and break till lump free",
                    "Work up with more pieces",
                    "When it is all broken pound till soft and soft"
                ]
            }

+ Response 201 (application/json)

    + Headers

            Location: /recipes/16
    
    + Body 

            {
                "id": 16,
                "recipeName": "Pounded Yam",
                "prepTime": "30 Minutes",
                "cookTime": "20 Minutes",
                "totalTime": "1 Hour",
                "difficulty": "A Bit Difficult",
                "extraInfo": "Can be eaten with any of the soups in my other recipes",
                "vegetarian": false,
                "recipeImage": null,
                "userId": 1,
                "ingredients": [
                    "1 tuber of yam"
                ],
                "preparations": [
                    "Cut Yam into small pieces",
                    "Make sure every thing that isn't yam is removed from the cut pieces",
                    "Boil Yam in plain water (without salt) till soft, but not too soft"
                ],
                "directions": [
                    "Put about 2 pieces of yam and break till lump free",
                    "Work up with more pieces",
                    "When it is all broken pound till soft and soft"
                ],
                "updatedAt": "2017-11-02T11:18:48.820Z",
                "createdAt": "2017-11-02T11:18:48.820Z"
            }

## Get Recipes with the Most Upvotes [GET /recipes{?sort,order,page,limit}]

+ Parameters
    + sort: upvotes (string, required) - String to be sorted by.
    + order: ascending (string, required) - Order to be arranged by. 
    + page: 3 (number, optional) - Page number to show.
    + limit: 10 (number, optional) - Number of items per page. 

+ Request (application/json)

    + Headers

            token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTE1NDQ0NzkwLCJleHAiOjE1MTU1MzExOTB9.6d1VznIz8slZFioUzvC4KNGDlz_YsUNy95g2LPaEnJE'

+ Response 200 (application/json)

        [
            {
                "id": 10,
                "recipeName": "Peppered Chicken",
                "recipeImage": null,
                "prepTime": "30 Minutes",
                "cookTime": "20 Minutes",
                "totalTime": "1 Hour",
                "difficulty": "Normal",
                "extraInfo": "Nigerian Party Staple",
                "vegetarian": false,
                "ingredients": [
                    "1 Cup of Tomato Stew",
                    "1 Kilo of Chicken"
                ],
                "preparations": [
                    "Cut the chicken into small pieces, season and leave to marinate for 1 hour. This can be done in advance to save time",
                    "Boil on low heat for 25 minutes with little water to cook and preserve the chicken stock."
                ],
                "directions": [
                    "Put already fried tomato stew on fire, add little water and seasoning to taste",
                    "Add chicken and stir",
                    "Simmer on low heat for 3 minutes"
                ],
                "upvotes": 10,
                "downvotes": 0,
                "views": 50,
                "createdAt": "2017-10-30T00:47:03.687Z",
                "updatedAt": "2017-10-30T00:47:03.687Z",
                "userId": 2,
                "rating": "4.0000000000000000"
            },
            {
                "id": 5,
                "recipeName": "Egusi Soup",
                "recipeImage": null,
                "prepTime": "10 Minutes",
                "cookTime": "30 Minutes",
                "totalTime": "40 Minutes",
                "difficulty": "Normal",
                "extraInfo": "",
                "vegetarian": false,
                "ingredients": [
                    "2 Cups of Ground Egusi",
                    "1 Kilo of Chicken"
                ],
                "preparations": [
                    "Cut the chicken into small pieces, season and leave to marinate for 1 hour. This can be done in advance to save time",
                    "Boil on low heat for 25 minutes with little water to cook and preserve the chicken stock."
                ],
                "directions": [
                    "Fry Onions in Palm Oil till transluscent",
                    "Add Egusi and fry till oil separates from egusi"
                ],
                "upvotes": 9,
                "downvotes": 0,
                "views": 30,
                "createdAt": "2017-10-30T00:47:03.687Z",
                "updatedAt": "2017-10-30T00:47:03.687Z",
                "userId": 6,
                "rating": "4.5000000000000000"
            },
            {
                "id": 15,
                "recipeName": "White Soup",
                "recipeImage": null,
                "prepTime": "30 Minutes",
                "cookTime": "20 Minutes",
                "totalTime": "1 Hour",
                "difficulty": "Normal",
                "extraInfo": "Nigerian Party Staple",
                "vegetarian": false,
                "ingredients": [
                    "1 Kilo of Chicken"
                ],
                "preparations": [
                    "Cut the chicken into small pieces, season and leave to marinate for 1 hour. This can be done in advance to save time",
                    "Boil on low heat for 25 minutes with little water to cook and preserve the chicken stock."
                ],
                "directions": [
                    "I don't even know how to cook white soup"
                ],
                "upvotes": 7,
                "downvotes": 2,
                "views": 49,
                "createdAt": "2017-10-30T00:47:03.687Z",
                "updatedAt": "2017-10-30T00:47:03.687Z",
                "userId": 8,
                "rating": "5.0000000000000000"
            },
            {
                "id": 11,
                "recipeName": "Mixed Okro Soup (Obe Ila Asepo)",
                "recipeImage": null,
                "prepTime": "10 Minutes",
                "cookTime": "30 Minutes",
                "totalTime": "40 Minutes",
                "difficulty": "Normal",
                "extraInfo": "",
                "vegetarian": false,
                "ingredients": [
                    "Okro",
                    "1 Kilo of Chicken"
                ],
                "preparations": [
                    "Cut the chicken into small pieces, season and leave to marinate for 1 hour. This can be done in advance to save time",
                    "Boil on low heat for 25 minutes with little water to cook and preserve the chicken stock."
                ],
                "directions": [
                    "Add Okro to little boiling water and beat until it draws",
                    "Add ingredients"
                ],
                "upvotes": 6,
                "downvotes": 3,
                "views": 27,
                "createdAt": "2017-10-30T00:47:03.687Z",
                "updatedAt": "2017-10-30T00:47:03.687Z",
                "userId": 6,
                "rating": "5.0000000000000000"
            },
            {
                "id": 7,
                "recipeName": "Chicken Stew",
                "recipeImage": null,
                "prepTime": "30 Minutes",
                "cookTime": "30 Minutes",
                "totalTime": "1 Hour",
                "difficulty": "Normal",
                "extraInfo": "Nigerian Party Staple",
                "vegetarian": false,
                "ingredients": [
                    "Stew Base",
                    "1 Kilo of Chicken"
                ],
                "preparations": [
                    "Cut the chicken into small pieces, season and leave to marinate for 1 hour. This can be done in advance to save time",
                    "Boil on low heat for 25 minutes with little water to cook and preserve the chicken stock."
                ],
                "directions": [
                    "Fry already boiled stew base till done",
                    "Add chicken stock and ingredients to taste"
                ],
                "upvotes": 5,
                "downvotes": 4,
                "views": 20,
                "createdAt": "2017-10-30T00:47:03.687Z",
                "updatedAt": "2017-10-30T00:47:03.687Z",
                "userId": 9,
                "rating": "3.0000000000000000"
            },
            ...
        ]       

## Search Recipes by Name or Ingredients [GET /recipes{?search,page,limit}]

+ Parameters
    + search: rice (string, required) - String to search for.
    + page: 3 (number, optional) - Page number to show.
    + limit: 10 (number, optional) - Number of items per page. 

+ Request (application/json)

    + Headers

            token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTE1NDQ0NzkwLCJleHAiOjE1MTU1MzExOTB9.6d1VznIz8slZFioUzvC4KNGDlz_YsUNy95g2LPaEnJE'

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "recipeName": "Coconut Rice",
                "recipeImage": null,
                "prepTime": "30 Minutes",
                "cookTime": "20 Minutes",
                "totalTime": "1 Hour",
                "difficulty": "Normal",
                "extraInfo": "",
                "vegetarian": false,
                "ingredients": [
                    "2 Cups of Rice",
                    "1 Coconut"
                ],
                "preparations": [
                    "Cut the chicken into small pieces, season and leave to marinate for 1 hour. This can be done in advance to save time",
                    "Boil on low heat for 25 minutes with little water to cook and preserve the chicken stock.",
                    "Grate coconut and strain milk from it by boiling for a few minutes"
                ],
                "directions": [
                    "Parboil Rice till half done",
                    "Put already fried tomato stew on fire, add water and seasoning to taste"
                ],
                "createdAt": "2017-10-30T00:47:03.687Z",
                "updatedAt": "2017-10-30T00:47:03.687Z",
                "userId": 1,
                "rating": "3.5000000000000000",
                "likes": [
                    {
                        "upvote": true
                    },
                    {
                        "upvote": true
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    }
                ]
            },
            {
                "id": 2,
                "recipeName": "Fried Rice",
                "recipeImage": null,
                "prepTime": "30 Minutes",
                "cookTime": "20 Minutes",
                "totalTime": "1 Hour",
                "difficulty": "Normal",
                "extraInfo": "Nigerian Party Staple",
                "vegetarian": false,
                "ingredients": [
                    "2 Cups of Rice",
                    "1 Kilo of Chicken"
                ],
                "preparations": [
                    "Cut the chicken into small pieces, season and leave to marinate for 1 hour. This can be done in advance to save time",
                    "Boil on low heat for 25 minutes with little water to cook and preserve the chicken stock.",
                    "Cut ingredients into small pieces"
                ],
                "directions": [
                    "Parboil Rice till half done",
                    "Steam ingredients in oil till almost soft"
                ],
                "createdAt": "2017-10-30T00:47:03.687Z",
                "updatedAt": "2017-10-30T00:47:03.687Z",
                "userId": 2,
                "rating": "4.5000000000000000",
                "likes": [
                    {
                        "upvote": true
                    },
                    {
                        "upvote": true
                    },
                    {
                        "upvote": true
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    }
                ]
            },
            {
                "id": 3,
                "recipeName": "Rice and Beans",
                "recipeImage": null,
                "prepTime": "30 Minutes",
                "cookTime": "20 Minutes",
                "totalTime": "1 Hour",
                "difficulty": "Normal",
                "extraInfo": "",
                "vegetarian": false,
                "ingredients": [
                    "2 Cups of Rice",
                    "1.5 Cups of Beans",
                    "1 kilo of chicken"
                ],
                "preparations": [
                    "Cut the chicken into small pieces, season and leave to marinate for 1 hour. This can be done in advance to save time",
                    "Boil on low heat for 25 minutes with little water to cook and preserve the chicken stock."
                ],
                "directions": [
                    "Parboil Rice till half done",
                    "Cook beans with onions till almost done"
                ],
                "createdAt": "2017-10-30T00:47:03.687Z",
                "updatedAt": "2017-10-30T00:47:03.687Z",
                "userId": 3,
                "rating": "5.0000000000000000",
                "likes": [
                    {
                        "upvote": true
                    },
                    {
                        "upvote": true
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    }
                ]
            },
            {
                "id": 9,
                "recipeName": "Jollof Rice",
                "recipeImage": null,
                "prepTime": "30 Minutes",
                "cookTime": "20 Minutes",
                "totalTime": "1 Hour",
                "difficulty": "Normal",
                "extraInfo": "Nigerian Party Staple",
                "vegetarian": false,
                "ingredients": [
                    "2 Cups of Rice",
                    "1 Kilo of Chicken"
                ],
                "preparations": [
                    "Cut the chicken into small pieces, season and leave to marinate for 1 hour. This can be done in advance to save time",
                    "Boil on low heat for 25 minutes with little water to cook and preserve the chicken stock."
                ],
                "directions": [
                    "Parboil Rice till half done",
                    "Put already fried tomato stew on fire, add water and seasoning to taste"
                ],
                "createdAt": "2017-10-30T00:47:03.687Z",
                "updatedAt": "2017-10-30T00:47:03.687Z",
                "userId": 1,
                "rating": "3.0000000000000000",
                "likes": [
                    {
                        "upvote": true
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    },
                    {
                        "upvote": false
                    }
                ]
            }
        ]

## Get/Modify/Delete Recipe [/recipes/{recipeId}]

+ Parameters
    + recipeId: `16` (number, required) - ID of the Recipe in form of an integer

### Get a Recipe [GET]

+ Request (application/json)

    + Headers

            token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTE1NDQ0NzkwLCJleHAiOjE1MTU1MzExOTB9.6d1VznIz8slZFioUzvC4KNGDlz_YsUNy95g2LPaEnJE'

+ Response 200 (application/json)

    + Body 

            {
                "id": 15,
                "recipeName": "White Soup",
                "recipeImage": null,
                "prepTime": "30 Minutes",
                "cookTime": "20 Minutes",
                "totalTime": "1 Hour",
                "difficulty": "Normal",
                "extraInfo": "Nigerian Party Staple",
                "vegetarian": false,
                "ingredients": [
                    "1 Kilo of Chicken"
                ],
                "preparations": [
                    "Cut the chicken into small pieces, season and leave to marinate for 1 hour. This can be done in advance to save time",
                    "Boil on low heat for 25 minutes with little water to cook and preserve the chicken stock."
                ],
                "directions": [
                    "I don't even know how to cook white soup"
                ],
                "upvotes": 7,
                "downvotes": 2,
                "views": 50,
                "createdAt": "2017-10-30T00:47:03.687Z",
                "updatedAt": "2017-10-30T00:47:03.687Z",
                "userId": 8,
                "rating": "5.0000000000000000",
                "reviews": [
                    {
                        "rating": 5,
                        "comment": "Excellent",
                        "userId": 6
                    }
                ]
            }

### Modify Recipe [PUT]

This action allows you to modify an existing recipe added by you.

+ Attributes

    + recipeName (string, required) - Recipe Name
    + prepTime (string, optional) - Recipe Preparation Time
    + cookTime (string, optional) - Recipe Cook Time
    + totalTime (string, required) - Total Time
    + difficulty (enum[string], optional) - A List of Strings to Choose from
    + extraInfo (string, optional) - Extra Information about Recipe
    + vegetarian (string, optional) - Boolean showing if suitable for vegetarians
    + ingredients (array, required) - Array of ingredients
    + preparations (array, optional) - Array of preparation steps
    + directions (array, required) - Array of direction steps

    + Difficulty Values
        + `Easy`
        + `Normal`
        + `A Bit Difficult'
        + `Difficult'
        + `Very Difficult'

+ Request (application/json)

    + Headers

            token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTE1NDQ0NzkwLCJleHAiOjE1MTU1MzExOTB9.6d1VznIz8slZFioUzvC4KNGDlz_YsUNy95g2LPaEnJE'

    + Body

            {
                "ingredients": ["1 medium tuber of yam"],
            }

+ Response 200 (application/json)

    + Headers

            Location: /recipes/16
    
    + Body 

            {
                "id": 16,
                "recipeName": "Pounded Yam",
                "prepTime": "30 Minutes",
                "cookTime": "20 Minutes",
                "totalTime": "1 Hour",
                "difficulty": "A Bit Difficult",
                "extraInfo": "Can be eaten with any of the soups in my other recipes",
                "vegetarian": false,
                "ingredients": [
                    "1 medium tuber of yam"
                ],
                "preparations": [
                    "Cut Yam into small pieces",
                    "Make sure every thing that isn't yam is removed from the cut pieces",
                    "Boil Yam in plain water (without salt) till soft, but not too soft"
                ],
                "directions": [
                    "Put about 2 pieces of yam and break till lump free",
                    "Work up with more pieces",
                    "When it is all broken pound till soft and soft"
                ],
                "upvotes": 0,
                "downvotes": 0,
                "views": 0,
                "createdAt": "2017-11-02T11:18:48.820Z",
                "updatedAt": "2017-11-02T11:18:48.820Z",
                "userId": 1,
                "rating": "0",
                "reviews": []
            }

### Delete Recipe [DELETE]

This action allows you to delete an existing recipe added by you.

+ Request (application/json)

    + Headers

            token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTE1NDQ0NzkwLCJleHAiOjE1MTU1MzExOTB9.6d1VznIz8slZFioUzvC4KNGDlz_YsUNy95g2LPaEnJE'

+ Response 204(application/json)

## Upvote a Recipe [POST /recipes/{recipeId}/upvotes]

You may upvote recipes using this action. It takes no input. Sending it again will unvote the recipe.

+ Parameters
    + recipeId: `4` (number, required) - ID of the Recipe to upvote in form of an integer.

+ Request (application/json)

    + Headers

            token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTE1NDQ0NzkwLCJleHAiOjE1MTU1MzExOTB9.6d1VznIz8slZFioUzvC4KNGDlz_YsUNy95g2LPaEnJE'

+ Response 201 (application/json)

    + Headers

            Location: /recipes/4/upvotes/62
    
    + Body

            {
                message: 'Your vote has been recored',
                upvotes: 12,
                downvotes: 1
            }

## Downvote a Recipe [POST /recipes/{recipeId}/downvotes]

You may downvote recipes using this action. It takes no input. Sending it again will unvote the recipe.

+ Parameters
    + recipeId: `4` (number, required) - ID of the Recipe to downvote in form of an integer.

+ Request (application/json)

    + Headers

            token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTE1NDQ0NzkwLCJleHAiOjE1MTU1MzExOTB9.6d1VznIz8slZFioUzvC4KNGDlz_YsUNy95g2LPaEnJE'

+ Response 201 (application/json)

    + Headers

            Location: /recipes/4/downvotes/63
    
    + Body

            {
                message: 'Your vote has been recored',
                upvotes: 11,
                downvotes: 2
            }

## Review a Recipe [POST /recipes/{recipeId}/reviews]

You may review a recipe using this action. It takes a JSON object containing a review.

+ Parameters
    + recipeId: `8` (number, required) - ID of the Recipe to review in form of an integer.

+ Attributes 

    + rating (number, required)  - A number from 1 - 5 with 1 being the lowest and 5 being the highest rating.
    + comment (string, optional) - A comment to add to the review.

+ Request (application/json)
    + Headers

            token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTE1NDQ0NzkwLCJleHAiOjE1MTU1MzExOTB9.6d1VznIz8slZFioUzvC4KNGDlz_YsUNy95g2LPaEnJE'

    + Body

            {
                "rating": 5,
                "comment": "Excellent Recipe. Loved it"
            }

+ Response 201 (application/json)

    + Headers

            Location: /recipes/8/reviews/22
    
    + Body

            {
                "id": 22,
                "rating": 5,
                "comment": "Excellent Recipe. Loved it",
                "recipeId": 8,
                "userId": 1,
                "updatedAt": "2017-11-02T11:55:26.941Z",
                "createdAt": "2017-11-02T11:55:26.941Z"
            }

## Add a Recipe to Favorites [POST /recipes/{recipeId}/favorites]

You may add a recipe to your favorite recipes using this action. It takes no input. Sending it again will unfavorite the recipe.

+ Parameters
    + recipeId: `4` (number, required) - ID of the Recipe to add to favorites in form of an integer.

+ Request (application/json)

    + Headers

            token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTE1NDQ0NzkwLCJleHAiOjE1MTU1MzExOTB9.6d1VznIz8slZFioUzvC4KNGDlz_YsUNy95g2LPaEnJE'

+ Response 201 (application/json)

    + Headers

            Location: /recipes/4/favorites/6
        
    + Body
    
            {
                "message": "Recipe has been added to favorites",
                "recipes": [
                    {
                        "id": 5,
                        "recipeName": "Egusi Soup",
                        "recipeImage": null,
                        "prepTime": "10 Minutes",
                        "cookTime": "30 Minutes",
                        "totalTime": "40 Minutes",
                        "difficulty": "Normal",
                        "extraInfo": "",
                        "vegetarian": false,
                        "ingredients": [
                            "2 Cups of Ground Egusi",
                            "1 Kilo of Chicken"
                        ],
                        "preparations": [
                            "Cut the chicken into small pieces, season and leave to marinate for 1 hour. This can be done in advance to save time",
                            "Boil on low heat for 25 minutes with little water to cook and preserve the chicken stock."
                        ],
                        "directions": [
                            "Fry Onions in Palm Oil till transluscent",
                            "Add Egusi and fry till oil separates from egusi"
                        ],
                        "upvotes": 9,
                        "downvotes": 0,
                        "views": 30,
                        "createdAt": "2017-10-30T00:47:03.687Z",
                        "updatedAt": "2017-10-30T00:47:03.687Z",
                        "userId": 6
                    },
                    {
                        "id": 11,
                        "recipeName": "Mixed Okro Soup (Obe Ila Asepo)",
                        "recipeImage": null,
                        "prepTime": "10 Minutes",
                        "cookTime": "30 Minutes",
                        "totalTime": "40 Minutes",
                        "difficulty": "Normal",
                        "extraInfo": "",
                        "vegetarian": false,
                        "ingredients": [
                            "Okro",
                            "1 Kilo of Chicken"
                        ],
                        "preparations": [
                            "Cut the chicken into small pieces, season and leave to marinate for 1 hour. This can be done in advance to save time",
                            "Boil on low heat for 25 minutes with little water to cook and preserve the chicken stock."
                        ],
                        "directions": [
                            "Add Okro to little boiling water and beat until it draws",
                            "Add ingredients"
                        ],
                        "upvotes": 6,
                        "downvotes": 3,
                        "views": 27,
                        "createdAt": "2017-10-30T00:47:03.687Z",
                        "updatedAt": "2017-10-30T00:47:03.687Z",
                        "userId": 6
                    },
                    {
                        "id": 10,
                        "recipeName": "Peppered Chicken",
                        "recipeImage": null,
                        "prepTime": "30 Minutes",
                        "cookTime": "20 Minutes",
                        "totalTime": "1 Hour",
                        "difficulty": "Normal",
                        "extraInfo": "Nigerian Party Staple",
                        "vegetarian": false,
                        "ingredients": [
                            "1 Cup of Tomato Stew",
                            "1 Kilo of Chicken"
                        ],
                        "preparations": [
                            "Cut the chicken into small pieces, season and leave to marinate for 1 hour. This can be done in advance to save time",
                            "Boil on low heat for 25 minutes with little water to cook and preserve the chicken stock."
                        ],
                        "directions": [
                            "Put already fried tomato stew on fire, add little water and seasoning to taste",
                            "Add chicken and stir",
                            "Simmer on low heat for 3 minutes"
                        ],
                        "upvotes": 10,
                        "downvotes": 0,
                        "views": 50,
                        "createdAt": "2017-10-30T00:47:03.687Z",
                        "updatedAt": "2017-10-30T00:47:03.687Z",
                        "userId": 2
                    },
                    ...
                ]       
            }
